- style.css
Following the reorg of assets, path to logo needed to be updated.
> Fix path to Enarx white logo

- .github/workflows/ci.yml
- docusaurus.config.js
- package.json
- yarn.lock
This PR adds the search functionality to the website using the [docusaurus-search-local](https://github.com/easyops-cn/docusaurus-search-local) plugin.
> FEAT: Add search functionality using community plugin

- docs/Technical/Process-Flow.md
- docs/Technical/Threat.md
- docs/Technical/Trust-Architecture.md
Take 2! I managed to accidentally close the first PR with an erroneous git push, sorry for the noise :confused:
Original URLs return 404.
> Fix URLs to images

- docs/Contributing/Issues.md
- docs/Contributing/Lab.md
Changed "and" to "an" in line 31, Issues.md, and in line 56, Lab.md.
Doesn't close any other issue.
> Fixed typos in Issues.md and Lab.md

- docs/Contributing/Git-hook.md
- sidebars.js
I wrote this pretty quickly so feel free to change anything.
I added a check to see if the internal dir exists and to skip those to make the script a bit more compatible with other repos.
Closes [#1286](https://github.com/enarx/enarx/issues/1286) (issue in main enarx repo)
> Add documentation on setting up a pre-push hook.

- docs/Installation/Enarx.md
- docs/Installation/Setup.md
Signed-off-by: Paul Pietkiewicz <paul@profian.com>
> Modify installation instructions to be compatible with Enarx 0.2.0

- docs/Installation/Wasm.md
Signed-off-by: Mayank Kumar <mayank22oct@gmail.com>
> docs(kvm): kvm usage while running enarx

- src/pages/2022-03-29-open-source-101.md
- src/pages/events.mdx
> Add Open Source 101 to upcoming events

- docs/WebAssembly/Introduction.md
- sidebars.js
Starting template for issue #93 
> Add WebAssembly Guide

- package.json
- yarn.lock
Upgrade Docusaurus to latest version.
> Bump Docusaurus to version 2.0.0-beta.17

- docusaurus.config.js
- package.json
- src/pages/webinars.md
- yarn.lock
Update website menu with 3 sections: Docs, Resources, and Community.
> Update Website Menu

- src/pages/webinars.md
Update webinar page with videos
> Update webinar page

- src/pages/webinars.md
Update Veracruz webinar slides
> Update Veracruz webinar

- src/css/custom.css
Make iframe for video and slides responsive on mobile.
> Make video responsive

- src/css/custom.css
Make the video tag responsive on mobile
> Make video tag responsive

- src/pages/webinars.md
Add Exercism webinar from Sean McBride
> Add Exercism webinar

- docs/WebAssembly/Grain.md
Addresses issue #93 
Adding WebAssembly guide for Grain.
> WebAssembly Guide for Grain

- docs/WebAssembly/C++.md
- docs/WebAssembly/C.md
- docs/WebAssembly/Golang.md
- docs/WebAssembly/Grain.md
- docs/WebAssembly/Rust.md
Edit WebAssembly Guide text for clarity
> Edit WebAssembly Guide

- docs/Networking/Introduction.md
- docs/Networking/ROT13.md
- docs/Networking/TCP-Server.md
- sidebars.js
Add Networking Guide with TCP Echo Server example and ROT13 cipher video from @moksh-pathak
> Add Networking Guide

- docusaurus.config.js
Add Networking Guide to top and footer menu
> Add Networking Guide to menu

- docs/Contributing/Code.md
Cargo make is not used anymore.
> docs: remove reference to cargo make

- resources/2022-02-10-balmoral-castle.md
- resources/2022-03-15-chittorgarh-fort.md
- resources/2022-03-16-enarx-0-3-0.md
- resources/authors.yml
Add Enarx 0.3.0 posts to Resources:
- Enarx's Blog
- Mike's Blog
Add Paul as author for release notes.
> docs: add Enarx 0.3.0 posts to resources

- docs/WebAssembly/AssemblyScript.md
Addresses #93 
Added WebAssembly guide demo for AssemblyScript.
> WebAssembly guide demo for AssemblyScript

- docs/WebAssembly/AssemblyScript.md
- sidebars.js
> Add AssemblyScript sidebar

- resources/2022-03-16-profian-wasm.md
Add Profian's blog post about the "WebAssembly ecosystem" to Resources
> Add Profian blog post wrt Wasm

- docusaurus.config.js
Add search functionality from Algolia DocSearch
Closes #135 
> feat: add search functionality

- docusaurus.config.js
- package.json
- yarn.lock
Mermaid support for MDX.
Closes #137 
> feat: add mermaid support

- src/pages/webinars.md
Add Suborbital video by Connor Hicks to Webinar page.
> docs: add suborbital webinar

- src/pages/webinars.md
> docs: fix webinar links

- .github/workflows/commisery.yml
> feat(gh_actions): enforce conventional commits

- package.json
- yarn.lock
Bump Docusaurus to latest version.
> fix: bump Docusaurus to version 2.0.0-beta.18

- src/pages/webinars.md
Add Erica Brescia fireside chat to the Webinars page.
> docs: add Erica Brescia webinar

- resources/2022-03-15-chittorgarh-fort.md
- resources/2022-03-21-commits-stars.md
Add 1500 commits & 500 stars blog post to Resources
> docs: add 500 stars blog post

- docs/WebAssembly/C++.md
> docs: fix typo

- docs/WebAssembly/C.md
> docs: fix typo in c

- docs/WebAssembly/TypeScript.md
- sidebars.js
> docs: add typescript guide

- src/pages/webinars.md
> docs: add Shraddha's FOSSASIA video

- docs/WebAssembly/dotnet.md
- sidebars.js
> docs: add dotnet guide

- docs/WebAssembly/Python.md
- sidebars.js
Add Python tutorial to sidebar. Enarx support is a WIP.
> docs: add Python to sidebar

- docs/WebAssembly/C.md
> docs: add c guide

- docs/WebAssembly/C.md
- docs/WebAssembly/JavaScript.md
> docs: add quick short note

- resources/2022-03-21-commits-stars.md
- resources/2022-04-12-enarx-0-4-0.md
- resources/2022-04-12-wasm-lang.md
Add blog posts about the 0.4.0 release from Mike and Paul to Resources
> docs: add 0.4.0 blog posts to Resources

- src/pages/webinars.md
Add CCC fireside chat from Mike and Stephen about the book "Trust in computer systems and the Cloud"
> docs: add Mike's webinar about Trust book

- docs/WebAssembly/Swift.md
Signed-off-by: Moksh Pathak <pathakmoksh@gmail.com>
Addresses issue #93
This Pull Request adds documentation for Swift Wasm WebAssembly guide.
> docs: add swift guide
